[package]
name = "avosetta-macros"
description = "A fast, minimal html templating language for Rust."
version = "0.1.1"
authors = [ "Callum Hopkins" ]
edition = "2024"
license = "MIT"
repository = "https://github.com/callum-hopkins-dev/avosetta"
readme = "README.md"
documentation = "https://docs.rs/avosetta"
keywords = [ "web", "proc-macro", "html", "template", "encode" ]
categories = [ "web-programming", "template-engine", "encoding" ]

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.3.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full"] }
